name: metaphlan
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9.*
  - click=8.1.*
  - click-default-group=1.2.*
  - pandas=1.5.*
  - snakemake=7.20.*
  - metaphlan=3.0.14
