name: short-read-taxonomy
channels:
  - conda-forge
  - bioconda
  - defaults
  - R
dependencies:
  - click=8.1.3
  - click-default-group==1.2.2
  - pandas==1.3.5
  - snakemake==7.8.5
  - r-essentials
  - kraken2=2.1.2
