name: short-read-taxonomy
channels:
  - conda-forge
  - bioconda
  - R
  - nodefaults
dependencies:
  - python=3.9.*
  - click=8.1.*
  - click-default-group=1.2.*
  - kraken2=2.1.*
  - pandas=1.5.*
  - r-essentials=4.2
  - snakemake=7.20.*
